apiVersion: v1
kind: Service
metadata:
  name: cache-demo-service
spec:
  type: NodePort
  selector:
    app: cache-demo-deployment 
  ports:
   - nodePort: 30162
     port: 8080
     targetPort: 8080   